### ISSUE TITLE
Tutorial website cannot be open

### ISSUE THREAD

**Issue by tiffanyXiaoqing** [MechatronicsBlog/RaspberryPi_TFLite_Qt#2]
I want to learn how to build tflite project with C++. Would you provide another way for us to read the tutorial?

**Comment by JaviBonilla** [comment]
Hi @tiffanyXiaoqing,

I can open it without any problem, could you check it again?

**Comment by tiffanyXiaoqing** [comment]
I can open it in my iPhone. Thank you!
